//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.22 at 11:46:25 AM CST 
//


package org.hibernate.internal.jaxb.mapping.hbm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for flush-mode-attribute.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="flush-mode-attribute">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="always"/>
 *     &lt;enumeration value="auto"/>
 *     &lt;enumeration value="never"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "flush-mode-attribute")
@XmlEnum
public enum JaxbFlushModeAttribute {

    @XmlEnumValue("always")
    ALWAYS("always"),
    @XmlEnumValue("auto")
    AUTO("auto"),
    @XmlEnumValue("never")
    NEVER("never");
    private final String value;

    JaxbFlushModeAttribute(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JaxbFlushModeAttribute fromValue(String v) {
        for (JaxbFlushModeAttribute c: JaxbFlushModeAttribute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
