//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.22 at 11:46:25 AM CST 
//


package org.hibernate.internal.jaxb.mapping.hbm;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for lazy-attribute-with-no-proxy.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="lazy-attribute-with-no-proxy">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="false"/>
 *     &lt;enumeration value="no-proxy"/>
 *     &lt;enumeration value="proxy"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "lazy-attribute-with-no-proxy")
@XmlEnum
public enum JaxbLazyAttributeWithNoProxy {

    @XmlEnumValue("false")
    FALSE("false"),
    @XmlEnumValue("no-proxy")
    NO_PROXY("no-proxy"),
    @XmlEnumValue("proxy")
    PROXY("proxy");
    private final String value;

    JaxbLazyAttributeWithNoProxy(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static JaxbLazyAttributeWithNoProxy fromValue(String v) {
        for (JaxbLazyAttributeWithNoProxy c: JaxbLazyAttributeWithNoProxy.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
