//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.22 at 11:46:25 AM CST 
//


package org.hibernate.internal.jaxb.mapping.orm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hibernate.internal.jaxb.mapping.orm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hibernate.internal.jaxb.mapping.orm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JaxbColumn }
     * 
     */
    public JaxbColumn createJaxbColumn() {
        return new JaxbColumn();
    }

    /**
     * Create an instance of {@link JaxbPrimaryKeyJoinColumn }
     * 
     */
    public JaxbPrimaryKeyJoinColumn createJaxbPrimaryKeyJoinColumn() {
        return new JaxbPrimaryKeyJoinColumn();
    }

    /**
     * Create an instance of {@link JaxbJoinTable }
     * 
     */
    public JaxbJoinTable createJaxbJoinTable() {
        return new JaxbJoinTable();
    }

    /**
     * Create an instance of {@link JaxbOneToMany }
     * 
     */
    public JaxbOneToMany createJaxbOneToMany() {
        return new JaxbOneToMany();
    }

    /**
     * Create an instance of {@link JaxbCascadeType }
     * 
     */
    public JaxbCascadeType createJaxbCascadeType() {
        return new JaxbCascadeType();
    }

    /**
     * Create an instance of {@link JaxbAttributeOverride }
     * 
     */
    public JaxbAttributeOverride createJaxbAttributeOverride() {
        return new JaxbAttributeOverride();
    }

    /**
     * Create an instance of {@link JaxbElementCollection }
     * 
     */
    public JaxbElementCollection createJaxbElementCollection() {
        return new JaxbElementCollection();
    }

    /**
     * Create an instance of {@link JaxbPersistenceUnitMetadata }
     * 
     */
    public JaxbPersistenceUnitMetadata createJaxbPersistenceUnitMetadata() {
        return new JaxbPersistenceUnitMetadata();
    }

    /**
     * Create an instance of {@link JaxbOrderColumn }
     * 
     */
    public JaxbOrderColumn createJaxbOrderColumn() {
        return new JaxbOrderColumn();
    }

    /**
     * Create an instance of {@link JaxbEntityResult }
     * 
     */
    public JaxbEntityResult createJaxbEntityResult() {
        return new JaxbEntityResult();
    }

    /**
     * Create an instance of {@link JaxbNamedNativeQuery }
     * 
     */
    public JaxbNamedNativeQuery createJaxbNamedNativeQuery() {
        return new JaxbNamedNativeQuery();
    }

    /**
     * Create an instance of {@link JaxbEntityListener }
     * 
     */
    public JaxbEntityListener createJaxbEntityListener() {
        return new JaxbEntityListener();
    }

    /**
     * Create an instance of {@link JaxbPreRemove }
     * 
     */
    public JaxbPreRemove createJaxbPreRemove() {
        return new JaxbPreRemove();
    }

    /**
     * Create an instance of {@link JaxbMapKey }
     * 
     */
    public JaxbMapKey createJaxbMapKey() {
        return new JaxbMapKey();
    }

    /**
     * Create an instance of {@link JaxbSecondaryTable }
     * 
     */
    public JaxbSecondaryTable createJaxbSecondaryTable() {
        return new JaxbSecondaryTable();
    }

    /**
     * Create an instance of {@link JaxbUniqueConstraint }
     * 
     */
    public JaxbUniqueConstraint createJaxbUniqueConstraint() {
        return new JaxbUniqueConstraint();
    }

    /**
     * Create an instance of {@link JaxbGeneratedValue }
     * 
     */
    public JaxbGeneratedValue createJaxbGeneratedValue() {
        return new JaxbGeneratedValue();
    }

    /**
     * Create an instance of {@link JaxbEntity }
     * 
     */
    public JaxbEntity createJaxbEntity() {
        return new JaxbEntity();
    }

    /**
     * Create an instance of {@link JaxbId }
     * 
     */
    public JaxbId createJaxbId() {
        return new JaxbId();
    }

    /**
     * Create an instance of {@link JaxbJoinColumn }
     * 
     */
    public JaxbJoinColumn createJaxbJoinColumn() {
        return new JaxbJoinColumn();
    }

    /**
     * Create an instance of {@link JaxbEmbeddedId }
     * 
     */
    public JaxbEmbeddedId createJaxbEmbeddedId() {
        return new JaxbEmbeddedId();
    }

    /**
     * Create an instance of {@link JaxbMapKeyJoinColumn }
     * 
     */
    public JaxbMapKeyJoinColumn createJaxbMapKeyJoinColumn() {
        return new JaxbMapKeyJoinColumn();
    }

    /**
     * Create an instance of {@link JaxbPostUpdate }
     * 
     */
    public JaxbPostUpdate createJaxbPostUpdate() {
        return new JaxbPostUpdate();
    }

    /**
     * Create an instance of {@link JaxbVersion }
     * 
     */
    public JaxbVersion createJaxbVersion() {
        return new JaxbVersion();
    }

    /**
     * Create an instance of {@link JaxbQueryHint }
     * 
     */
    public JaxbQueryHint createJaxbQueryHint() {
        return new JaxbQueryHint();
    }

    /**
     * Create an instance of {@link JaxbEmbeddableAttributes }
     * 
     */
    public JaxbEmbeddableAttributes createJaxbEmbeddableAttributes() {
        return new JaxbEmbeddableAttributes();
    }

    /**
     * Create an instance of {@link JaxbSqlResultSetMapping }
     * 
     */
    public JaxbSqlResultSetMapping createJaxbSqlResultSetMapping() {
        return new JaxbSqlResultSetMapping();
    }

    /**
     * Create an instance of {@link JaxbInheritance }
     * 
     */
    public JaxbInheritance createJaxbInheritance() {
        return new JaxbInheritance();
    }

    /**
     * Create an instance of {@link JaxbMapKeyColumn }
     * 
     */
    public JaxbMapKeyColumn createJaxbMapKeyColumn() {
        return new JaxbMapKeyColumn();
    }

    /**
     * Create an instance of {@link JaxbTable }
     * 
     */
    public JaxbTable createJaxbTable() {
        return new JaxbTable();
    }

    /**
     * Create an instance of {@link JaxbEmbeddable }
     * 
     */
    public JaxbEmbeddable createJaxbEmbeddable() {
        return new JaxbEmbeddable();
    }

    /**
     * Create an instance of {@link JaxbAttributes }
     * 
     */
    public JaxbAttributes createJaxbAttributes() {
        return new JaxbAttributes();
    }

    /**
     * Create an instance of {@link JaxbPostRemove }
     * 
     */
    public JaxbPostRemove createJaxbPostRemove() {
        return new JaxbPostRemove();
    }

    /**
     * Create an instance of {@link JaxbEntityMappings }
     * 
     */
    public JaxbEntityMappings createJaxbEntityMappings() {
        return new JaxbEntityMappings();
    }

    /**
     * Create an instance of {@link JaxbPostPersist }
     * 
     */
    public JaxbPostPersist createJaxbPostPersist() {
        return new JaxbPostPersist();
    }

    /**
     * Create an instance of {@link JaxbIdClass }
     * 
     */
    public JaxbIdClass createJaxbIdClass() {
        return new JaxbIdClass();
    }

    /**
     * Create an instance of {@link JaxbPrePersist }
     * 
     */
    public JaxbPrePersist createJaxbPrePersist() {
        return new JaxbPrePersist();
    }

    /**
     * Create an instance of {@link JaxbPersistenceUnitDefaults }
     * 
     */
    public JaxbPersistenceUnitDefaults createJaxbPersistenceUnitDefaults() {
        return new JaxbPersistenceUnitDefaults();
    }

    /**
     * Create an instance of {@link JaxbSequenceGenerator }
     * 
     */
    public JaxbSequenceGenerator createJaxbSequenceGenerator() {
        return new JaxbSequenceGenerator();
    }

    /**
     * Create an instance of {@link JaxbManyToMany }
     * 
     */
    public JaxbManyToMany createJaxbManyToMany() {
        return new JaxbManyToMany();
    }

    /**
     * Create an instance of {@link JaxbTableGenerator }
     * 
     */
    public JaxbTableGenerator createJaxbTableGenerator() {
        return new JaxbTableGenerator();
    }

    /**
     * Create an instance of {@link JaxbPostLoad }
     * 
     */
    public JaxbPostLoad createJaxbPostLoad() {
        return new JaxbPostLoad();
    }

    /**
     * Create an instance of {@link JaxbMappedSuperclass }
     * 
     */
    public JaxbMappedSuperclass createJaxbMappedSuperclass() {
        return new JaxbMappedSuperclass();
    }

    /**
     * Create an instance of {@link JaxbFieldResult }
     * 
     */
    public JaxbFieldResult createJaxbFieldResult() {
        return new JaxbFieldResult();
    }

    /**
     * Create an instance of {@link JaxbNamedQuery }
     * 
     */
    public JaxbNamedQuery createJaxbNamedQuery() {
        return new JaxbNamedQuery();
    }

    /**
     * Create an instance of {@link JaxbMapKeyClass }
     * 
     */
    public JaxbMapKeyClass createJaxbMapKeyClass() {
        return new JaxbMapKeyClass();
    }

    /**
     * Create an instance of {@link JaxbEmptyType }
     * 
     */
    public JaxbEmptyType createJaxbEmptyType() {
        return new JaxbEmptyType();
    }

    /**
     * Create an instance of {@link JaxbPreUpdate }
     * 
     */
    public JaxbPreUpdate createJaxbPreUpdate() {
        return new JaxbPreUpdate();
    }

    /**
     * Create an instance of {@link JaxbBasic }
     * 
     */
    public JaxbBasic createJaxbBasic() {
        return new JaxbBasic();
    }

    /**
     * Create an instance of {@link JaxbEmbedded }
     * 
     */
    public JaxbEmbedded createJaxbEmbedded() {
        return new JaxbEmbedded();
    }

    /**
     * Create an instance of {@link JaxbLob }
     * 
     */
    public JaxbLob createJaxbLob() {
        return new JaxbLob();
    }

    /**
     * Create an instance of {@link JaxbDiscriminatorColumn }
     * 
     */
    public JaxbDiscriminatorColumn createJaxbDiscriminatorColumn() {
        return new JaxbDiscriminatorColumn();
    }

    /**
     * Create an instance of {@link JaxbAssociationOverride }
     * 
     */
    public JaxbAssociationOverride createJaxbAssociationOverride() {
        return new JaxbAssociationOverride();
    }

    /**
     * Create an instance of {@link JaxbManyToOne }
     * 
     */
    public JaxbManyToOne createJaxbManyToOne() {
        return new JaxbManyToOne();
    }

    /**
     * Create an instance of {@link JaxbColumnResult }
     * 
     */
    public JaxbColumnResult createJaxbColumnResult() {
        return new JaxbColumnResult();
    }

    /**
     * Create an instance of {@link JaxbCollectionTable }
     * 
     */
    public JaxbCollectionTable createJaxbCollectionTable() {
        return new JaxbCollectionTable();
    }

    /**
     * Create an instance of {@link JaxbOneToOne }
     * 
     */
    public JaxbOneToOne createJaxbOneToOne() {
        return new JaxbOneToOne();
    }

    /**
     * Create an instance of {@link JaxbEntityListeners }
     * 
     */
    public JaxbEntityListeners createJaxbEntityListeners() {
        return new JaxbEntityListeners();
    }

    /**
     * Create an instance of {@link JaxbTransient }
     * 
     */
    public JaxbTransient createJaxbTransient() {
        return new JaxbTransient();
    }

}
