//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.22 at 11:46:23 AM CST 
//


package org.hibernate.internal.jaxb.cfg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="session-factory">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="mapping" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="jar" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="resource" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;choice maxOccurs="unbounded" minOccurs="0">
 *                     &lt;element name="class-cache">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="include" default="all">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *                                   &lt;enumeration value="all"/>
 *                                   &lt;enumeration value="non-lazy"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/attribute>
 *                             &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="usage" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}usage-attribute" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                     &lt;element name="collection-cache">
 *                       &lt;complexType>
 *                         &lt;complexContent>
 *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                             &lt;attribute name="collection" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                             &lt;attribute name="usage" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}usage-attribute" />
 *                           &lt;/restriction>
 *                         &lt;/complexContent>
 *                       &lt;/complexType>
 *                     &lt;/element>
 *                   &lt;/choice>
 *                   &lt;element name="event" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="listener" type="{http://www.hibernate.org/xsd/hibernate-configuration}listener-element" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="type" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}type-attribute" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="listener" type="{http://www.hibernate.org/xsd/hibernate-configuration}listener-element" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="security" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="grant" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="actions" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="entity-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="context" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sessionFactory",
    "security"
})
@XmlRootElement(name = "hibernate-configuration")
public class JaxbHibernateConfiguration {

    @XmlElement(name = "session-factory", required = true)
    protected JaxbHibernateConfiguration.JaxbSessionFactory sessionFactory;
    protected JaxbHibernateConfiguration.JaxbSecurity security;

    /**
     * Gets the value of the sessionFactory property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHibernateConfiguration.JaxbSessionFactory }
     *     
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory getSessionFactory() {
        return sessionFactory;
    }

    /**
     * Sets the value of the sessionFactory property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHibernateConfiguration.JaxbSessionFactory }
     *     
     */
    public void setSessionFactory(JaxbHibernateConfiguration.JaxbSessionFactory value) {
        this.sessionFactory = value;
    }

    /**
     * Gets the value of the security property.
     * 
     * @return
     *     possible object is
     *     {@link JaxbHibernateConfiguration.JaxbSecurity }
     *     
     */
    public JaxbHibernateConfiguration.JaxbSecurity getSecurity() {
        return security;
    }

    /**
     * Sets the value of the security property.
     * 
     * @param value
     *     allowed object is
     *     {@link JaxbHibernateConfiguration.JaxbSecurity }
     *     
     */
    public void setSecurity(JaxbHibernateConfiguration.JaxbSecurity value) {
        this.security = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="grant" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="actions" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="entity-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="context" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "grant"
    })
    public static class JaxbSecurity {

        protected List<JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant> grant;
        @XmlAttribute(required = true)
        protected String context;

        /**
         * Gets the value of the grant property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the grant property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGrant().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant }
         * 
         * 
         */
        public List<JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant> getGrant() {
            if (grant == null) {
                grant = new ArrayList<JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant>();
            }
            return this.grant;
        }

        /**
         * Gets the value of the context property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getContext() {
            return context;
        }

        /**
         * Sets the value of the context property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setContext(String value) {
            this.context = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="actions" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="entity-name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="role" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class JaxbGrant {

            @XmlAttribute(required = true)
            protected String actions;
            @XmlAttribute(name = "entity-name", required = true)
            protected String entityName;
            @XmlAttribute(required = true)
            protected String role;

            /**
             * Gets the value of the actions property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActions() {
                return actions;
            }

            /**
             * Sets the value of the actions property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActions(String value) {
                this.actions = value;
            }

            /**
             * Gets the value of the entityName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEntityName() {
                return entityName;
            }

            /**
             * Sets the value of the entityName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEntityName(String value) {
                this.entityName = value;
            }

            /**
             * Gets the value of the role property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRole() {
                return role;
            }

            /**
             * Sets the value of the role property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRole(String value) {
                this.role = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="property" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="mapping" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="jar" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="resource" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;choice maxOccurs="unbounded" minOccurs="0">
     *           &lt;element name="class-cache">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="include" default="all">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
     *                         &lt;enumeration value="all"/>
     *                         &lt;enumeration value="non-lazy"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/attribute>
     *                   &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="usage" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}usage-attribute" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *           &lt;element name="collection-cache">
     *             &lt;complexType>
     *               &lt;complexContent>
     *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                   &lt;attribute name="collection" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                   &lt;attribute name="usage" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}usage-attribute" />
     *                 &lt;/restriction>
     *               &lt;/complexContent>
     *             &lt;/complexType>
     *           &lt;/element>
     *         &lt;/choice>
     *         &lt;element name="event" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="listener" type="{http://www.hibernate.org/xsd/hibernate-configuration}listener-element" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="type" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}type-attribute" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="listener" type="{http://www.hibernate.org/xsd/hibernate-configuration}listener-element" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "property",
        "mapping",
        "classCacheOrCollectionCache",
        "event",
        "listener"
    })
    public static class JaxbSessionFactory {

        protected List<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty> property;
        protected List<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping> mapping;
        @XmlElements({
            @XmlElement(name = "class-cache", type = JaxbHibernateConfiguration.JaxbSessionFactory.JaxbClassCache.class),
            @XmlElement(name = "collection-cache", type = JaxbHibernateConfiguration.JaxbSessionFactory.JaxbCollectionCache.class)
        })
        protected List<Object> classCacheOrCollectionCache;
        protected List<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent> event;
        protected List<JaxbListenerElement> listener;
        @XmlAttribute
        protected String name;

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty }
         * 
         * 
         */
        public List<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty> getProperty() {
            if (property == null) {
                property = new ArrayList<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty>();
            }
            return this.property;
        }

        /**
         * Gets the value of the mapping property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the mapping property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMapping().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping }
         * 
         * 
         */
        public List<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping> getMapping() {
            if (mapping == null) {
                mapping = new ArrayList<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping>();
            }
            return this.mapping;
        }

        /**
         * Gets the value of the classCacheOrCollectionCache property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classCacheOrCollectionCache property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassCacheOrCollectionCache().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbClassCache }
         * {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbCollectionCache }
         * 
         * 
         */
        public List<Object> getClassCacheOrCollectionCache() {
            if (classCacheOrCollectionCache == null) {
                classCacheOrCollectionCache = new ArrayList<Object>();
            }
            return this.classCacheOrCollectionCache;
        }

        /**
         * Gets the value of the event property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the event property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEvent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent }
         * 
         * 
         */
        public List<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent> getEvent() {
            if (event == null) {
                event = new ArrayList<JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent>();
            }
            return this.event;
        }

        /**
         * Gets the value of the listener property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the listener property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getListener().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JaxbListenerElement }
         * 
         * 
         */
        public List<JaxbListenerElement> getListener() {
            if (listener == null) {
                listener = new ArrayList<JaxbListenerElement>();
            }
            return this.listener;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="class" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="include" default="all">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
         *             &lt;enumeration value="all"/>
         *             &lt;enumeration value="non-lazy"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="usage" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}usage-attribute" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class JaxbClassCache {

            @XmlAttribute(name = "class", required = true)
            protected String clazz;
            @XmlAttribute
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String include;
            @XmlAttribute
            protected String region;
            @XmlAttribute(required = true)
            protected JaxbUsageAttribute usage;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the include property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInclude() {
                if (include == null) {
                    return "all";
                } else {
                    return include;
                }
            }

            /**
             * Sets the value of the include property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInclude(String value) {
                this.include = value;
            }

            /**
             * Gets the value of the region property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegion() {
                return region;
            }

            /**
             * Sets the value of the region property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegion(String value) {
                this.region = value;
            }

            /**
             * Gets the value of the usage property.
             * 
             * @return
             *     possible object is
             *     {@link JaxbUsageAttribute }
             *     
             */
            public JaxbUsageAttribute getUsage() {
                return usage;
            }

            /**
             * Sets the value of the usage property.
             * 
             * @param value
             *     allowed object is
             *     {@link JaxbUsageAttribute }
             *     
             */
            public void setUsage(JaxbUsageAttribute value) {
                this.usage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="collection" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="region" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="usage" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}usage-attribute" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class JaxbCollectionCache {

            @XmlAttribute(required = true)
            protected String collection;
            @XmlAttribute
            protected String region;
            @XmlAttribute(required = true)
            protected JaxbUsageAttribute usage;

            /**
             * Gets the value of the collection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getCollection() {
                return collection;
            }

            /**
             * Sets the value of the collection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setCollection(String value) {
                this.collection = value;
            }

            /**
             * Gets the value of the region property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRegion() {
                return region;
            }

            /**
             * Sets the value of the region property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRegion(String value) {
                this.region = value;
            }

            /**
             * Gets the value of the usage property.
             * 
             * @return
             *     possible object is
             *     {@link JaxbUsageAttribute }
             *     
             */
            public JaxbUsageAttribute getUsage() {
                return usage;
            }

            /**
             * Sets the value of the usage property.
             * 
             * @param value
             *     allowed object is
             *     {@link JaxbUsageAttribute }
             *     
             */
            public void setUsage(JaxbUsageAttribute value) {
                this.usage = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="listener" type="{http://www.hibernate.org/xsd/hibernate-configuration}listener-element" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" use="required" type="{http://www.hibernate.org/xsd/hibernate-configuration}type-attribute" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "listener"
        })
        public static class JaxbEvent {

            protected List<JaxbListenerElement> listener;
            @XmlAttribute(required = true)
            protected JaxbTypeAttribute type;

            /**
             * Gets the value of the listener property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the listener property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getListener().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JaxbListenerElement }
             * 
             * 
             */
            public List<JaxbListenerElement> getListener() {
                if (listener == null) {
                    listener = new ArrayList<JaxbListenerElement>();
                }
                return this.listener;
            }

            /**
             * Gets the value of the type property.
             * 
             * @return
             *     possible object is
             *     {@link JaxbTypeAttribute }
             *     
             */
            public JaxbTypeAttribute getType() {
                return type;
            }

            /**
             * Sets the value of the type property.
             * 
             * @param value
             *     allowed object is
             *     {@link JaxbTypeAttribute }
             *     
             */
            public void setType(JaxbTypeAttribute value) {
                this.type = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="file" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="jar" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="package" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="resource" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class JaxbMapping {

            @XmlAttribute(name = "class")
            protected String clazz;
            @XmlAttribute
            protected String file;
            @XmlAttribute
            protected String jar;
            @XmlAttribute(name = "package")
            protected String _package;
            @XmlAttribute
            protected String resource;

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the file property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFile() {
                return file;
            }

            /**
             * Sets the value of the file property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFile(String value) {
                this.file = value;
            }

            /**
             * Gets the value of the jar property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getJar() {
                return jar;
            }

            /**
             * Sets the value of the jar property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setJar(String value) {
                this.jar = value;
            }

            /**
             * Gets the value of the package property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPackage() {
                return _package;
            }

            /**
             * Sets the value of the package property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPackage(String value) {
                this._package = value;
            }

            /**
             * Gets the value of the resource property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getResource() {
                return resource;
            }

            /**
             * Sets the value of the resource property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setResource(String value) {
                this.resource = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class JaxbProperty {

            @XmlValue
            protected String value;
            @XmlAttribute(required = true)
            protected String name;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

        }

    }

}
