//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.01.22 at 11:46:23 AM CST 
//


package org.hibernate.internal.jaxb.cfg;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.hibernate.internal.jaxb.cfg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.hibernate.internal.jaxb.cfg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSecurity }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSecurity createJaxbHibernateConfigurationJaxbSecurity() {
        return new JaxbHibernateConfiguration.JaxbSecurity();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant createJaxbHibernateConfigurationJaxbSecurityJaxbGrant() {
        return new JaxbHibernateConfiguration.JaxbSecurity.JaxbGrant();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent createJaxbHibernateConfigurationJaxbSessionFactoryJaxbEvent() {
        return new JaxbHibernateConfiguration.JaxbSessionFactory.JaxbEvent();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping createJaxbHibernateConfigurationJaxbSessionFactoryJaxbMapping() {
        return new JaxbHibernateConfiguration.JaxbSessionFactory.JaxbMapping();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbClassCache }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory.JaxbClassCache createJaxbHibernateConfigurationJaxbSessionFactoryJaxbClassCache() {
        return new JaxbHibernateConfiguration.JaxbSessionFactory.JaxbClassCache();
    }

    /**
     * Create an instance of {@link JaxbListenerElement }
     * 
     */
    public JaxbListenerElement createJaxbListenerElement() {
        return new JaxbListenerElement();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSessionFactory }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory createJaxbHibernateConfigurationJaxbSessionFactory() {
        return new JaxbHibernateConfiguration.JaxbSessionFactory();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbCollectionCache }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory.JaxbCollectionCache createJaxbHibernateConfigurationJaxbSessionFactoryJaxbCollectionCache() {
        return new JaxbHibernateConfiguration.JaxbSessionFactory.JaxbCollectionCache();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty }
     * 
     */
    public JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty createJaxbHibernateConfigurationJaxbSessionFactoryJaxbProperty() {
        return new JaxbHibernateConfiguration.JaxbSessionFactory.JaxbProperty();
    }

    /**
     * Create an instance of {@link JaxbHibernateConfiguration }
     * 
     */
    public JaxbHibernateConfiguration createJaxbHibernateConfiguration() {
        return new JaxbHibernateConfiguration();
    }

}
